name: script
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Python script
        env:      
          PATH: ${{secrets.PATH}}
        run: python env.PATH
