name: script
on: 
  pull_request:
    branches: [ "test" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Python script
        run: python .github/workflows/example.py
