name: script
on: 
  workflow_dispatch:
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Python script
        run: python .github/workflows/example.py
  
  api_call:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: API call
        run: curl -X GET https://restcountries.com/v3.1/alpha/mk
